//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace DataTreeViewDemo.Web
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class DcSEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“DcSEntities”部分中的连接字符串初始化新 DcSEntities 对象。
        /// </summary>
        public DcSEntities() : base("name=DcSEntities", "DcSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DcSEntities 对象。
        /// </summary>
        public DcSEntities(string connectionString) : base(connectionString, "DcSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DcSEntities 对象。
        /// </summary>
        public DcSEntities(EntityConnection connection) : base(connection, "DcSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ProductAffiProductCategory> ProductAffiProductCategories
        {
            get
            {
                if ((_ProductAffiProductCategories == null))
                {
                    _ProductAffiProductCategories = base.CreateObjectSet<ProductAffiProductCategory>("ProductAffiProductCategories");
                }
                return _ProductAffiProductCategories;
            }
        }
        private ObjectSet<ProductAffiProductCategory> _ProductAffiProductCategories;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ProductCategory> ProductCategories
        {
            get
            {
                if ((_ProductCategories == null))
                {
                    _ProductCategories = base.CreateObjectSet<ProductCategory>("ProductCategories");
                }
                return _ProductCategories;
            }
        }
        private ObjectSet<ProductCategory> _ProductCategories;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TiledRegion> TiledRegions
        {
            get
            {
                if ((_TiledRegions == null))
                {
                    _TiledRegions = base.CreateObjectSet<TiledRegion>("TiledRegions");
                }
                return _TiledRegions;
            }
        }
        private ObjectSet<TiledRegion> _TiledRegions;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Products EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// 用于向 ProductAffiProductCategories EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToProductAffiProductCategories(ProductAffiProductCategory productAffiProductCategory)
        {
            base.AddObject("ProductAffiProductCategories", productAffiProductCategory);
        }
    
        /// <summary>
        /// 用于向 ProductCategories EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToProductCategories(ProductCategory productCategory)
        {
            base.AddObject("ProductCategories", productCategory);
        }
    
        /// <summary>
        /// 用于向 TiledRegions EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTiledRegions(TiledRegion tiledRegion)
        {
            base.AddObject("TiledRegions", tiledRegion);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DCSModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Product 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="code">Code 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="canBeOrdered">CanBeOrdered 属性的初始值。</param>
        /// <param name="ifPurchasable">IfPurchasable 属性的初始值。</param>
        /// <param name="ifOption">IfOption 属性的初始值。</param>
        /// <param name="productLifeCycle">ProductLifeCycle 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        public static Product CreateProduct(global::System.Int32 id, global::System.String code, global::System.String name, global::System.Boolean canBeOrdered, global::System.Boolean ifPurchasable, global::System.Boolean ifOption, global::System.Int32 productLifeCycle, global::System.Int32 status)
        {
            Product product = new Product();
            product.Id = id;
            product.Code = code;
            product.Name = name;
            product.CanBeOrdered = canBeOrdered;
            product.IfPurchasable = ifPurchasable;
            product.IfOption = ifOption;
            product.ProductLifeCycle = productLifeCycle;
            product.Status = status;
            return product;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false, "Code");
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CanBeOrdered
        {
            get
            {
                return _CanBeOrdered;
            }
            set
            {
                OnCanBeOrderedChanging(value);
                ReportPropertyChanging("CanBeOrdered");
                _CanBeOrdered = StructuralObject.SetValidValue(value, "CanBeOrdered");
                ReportPropertyChanged("CanBeOrdered");
                OnCanBeOrderedChanged();
            }
        }
        private global::System.Boolean _CanBeOrdered;
        partial void OnCanBeOrderedChanging(global::System.Boolean value);
        partial void OnCanBeOrderedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IfPurchasable
        {
            get
            {
                return _IfPurchasable;
            }
            set
            {
                OnIfPurchasableChanging(value);
                ReportPropertyChanging("IfPurchasable");
                _IfPurchasable = StructuralObject.SetValidValue(value, "IfPurchasable");
                ReportPropertyChanged("IfPurchasable");
                OnIfPurchasableChanged();
            }
        }
        private global::System.Boolean _IfPurchasable;
        partial void OnIfPurchasableChanging(global::System.Boolean value);
        partial void OnIfPurchasableChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderCycle
        {
            get
            {
                return _OrderCycle;
            }
            set
            {
                OnOrderCycleChanging(value);
                ReportPropertyChanging("OrderCycle");
                _OrderCycle = StructuralObject.SetValidValue(value, "OrderCycle");
                ReportPropertyChanged("OrderCycle");
                OnOrderCycleChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderCycle;
        partial void OnOrderCycleChanging(Nullable<global::System.Int32> value);
        partial void OnOrderCycleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PurchaseCycle
        {
            get
            {
                return _PurchaseCycle;
            }
            set
            {
                OnPurchaseCycleChanging(value);
                ReportPropertyChanging("PurchaseCycle");
                _PurchaseCycle = StructuralObject.SetValidValue(value, "PurchaseCycle");
                ReportPropertyChanged("PurchaseCycle");
                OnPurchaseCycleChanged();
            }
        }
        private Nullable<global::System.Int32> _PurchaseCycle;
        partial void OnPurchaseCycleChanging(Nullable<global::System.Int32> value);
        partial void OnPurchaseCycleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IfOption
        {
            get
            {
                return _IfOption;
            }
            set
            {
                OnIfOptionChanging(value);
                ReportPropertyChanging("IfOption");
                _IfOption = StructuralObject.SetValidValue(value, "IfOption");
                ReportPropertyChanged("IfOption");
                OnIfOptionChanged();
            }
        }
        private global::System.Boolean _IfOption;
        partial void OnIfOptionChanging(global::System.Boolean value);
        partial void OnIfOptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductLifeCycle
        {
            get
            {
                return _ProductLifeCycle;
            }
            set
            {
                OnProductLifeCycleChanging(value);
                ReportPropertyChanging("ProductLifeCycle");
                _ProductLifeCycle = StructuralObject.SetValidValue(value, "ProductLifeCycle");
                ReportPropertyChanged("ProductLifeCycle");
                OnProductLifeCycleChanged();
            }
        }
        private global::System.Int32 _ProductLifeCycle;
        partial void OnProductLifeCycleChanging(global::System.Int32 value);
        partial void OnProductLifeCycleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ParameterDescription
        {
            get
            {
                return _ParameterDescription;
            }
            set
            {
                OnParameterDescriptionChanging(value);
                ReportPropertyChanging("ParameterDescription");
                _ParameterDescription = StructuralObject.SetValidValue(value, true, "ParameterDescription");
                ReportPropertyChanged("ParameterDescription");
                OnParameterDescriptionChanged();
            }
        }
        private global::System.String _ParameterDescription;
        partial void OnParameterDescriptionChanging(global::System.String value);
        partial void OnParameterDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = StructuralObject.SetValidValue(value, true, "Version");
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.String _Version;
        partial void OnVersionChanging(global::System.String value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Configuration
        {
            get
            {
                return _Configuration;
            }
            set
            {
                OnConfigurationChanging(value);
                ReportPropertyChanging("Configuration");
                _Configuration = StructuralObject.SetValidValue(value, true, "Configuration");
                ReportPropertyChanged("Configuration");
                OnConfigurationChanged();
            }
        }
        private global::System.String _Configuration;
        partial void OnConfigurationChanging(global::System.String value);
        partial void OnConfigurationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EngineCylinder
        {
            get
            {
                return _EngineCylinder;
            }
            set
            {
                OnEngineCylinderChanging(value);
                ReportPropertyChanging("EngineCylinder");
                _EngineCylinder = StructuralObject.SetValidValue(value, true, "EngineCylinder");
                ReportPropertyChanged("EngineCylinder");
                OnEngineCylinderChanged();
            }
        }
        private global::System.String _EngineCylinder;
        partial void OnEngineCylinderChanging(global::System.String value);
        partial void OnEngineCylinderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmissionStandard
        {
            get
            {
                return _EmissionStandard;
            }
            set
            {
                OnEmissionStandardChanging(value);
                ReportPropertyChanging("EmissionStandard");
                _EmissionStandard = StructuralObject.SetValidValue(value, true, "EmissionStandard");
                ReportPropertyChanged("EmissionStandard");
                OnEmissionStandardChanged();
            }
        }
        private global::System.String _EmissionStandard;
        partial void OnEmissionStandardChanging(global::System.String value);
        partial void OnEmissionStandardChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ManualAutomatic
        {
            get
            {
                return _ManualAutomatic;
            }
            set
            {
                OnManualAutomaticChanging(value);
                ReportPropertyChanging("ManualAutomatic");
                _ManualAutomatic = StructuralObject.SetValidValue(value, true, "ManualAutomatic");
                ReportPropertyChanged("ManualAutomatic");
                OnManualAutomaticChanged();
            }
        }
        private global::System.String _ManualAutomatic;
        partial void OnManualAutomaticChanging(global::System.String value);
        partial void OnManualAutomaticChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, "Color");
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private Nullable<global::System.Int32> _Color;
        partial void OnColorChanging(Nullable<global::System.Int32> value);
        partial void OnColorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ColorCode
        {
            get
            {
                return _ColorCode;
            }
            set
            {
                OnColorCodeChanging(value);
                ReportPropertyChanging("ColorCode");
                _ColorCode = StructuralObject.SetValidValue(value, true, "ColorCode");
                ReportPropertyChanged("ColorCode");
                OnColorCodeChanged();
            }
        }
        private global::System.String _ColorCode;
        partial void OnColorCodeChanging(global::System.String value);
        partial void OnColorCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Picture
        {
            get
            {
                return _Picture;
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true, "Picture");
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.String _Picture;
        partial void OnPictureChanging(global::System.String value);
        partial void OnPictureChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true, "Remark");
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatorId
        {
            get
            {
                return _CreatorId;
            }
            set
            {
                OnCreatorIdChanging(value);
                ReportPropertyChanging("CreatorId");
                _CreatorId = StructuralObject.SetValidValue(value, "CreatorId");
                ReportPropertyChanged("CreatorId");
                OnCreatorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatorId;
        partial void OnCreatorIdChanging(Nullable<global::System.Int32> value);
        partial void OnCreatorIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatorName
        {
            get
            {
                return _CreatorName;
            }
            set
            {
                OnCreatorNameChanging(value);
                ReportPropertyChanging("CreatorName");
                _CreatorName = StructuralObject.SetValidValue(value, true, "CreatorName");
                ReportPropertyChanged("CreatorName");
                OnCreatorNameChanged();
            }
        }
        private global::System.String _CreatorName;
        partial void OnCreatorNameChanging(global::System.String value);
        partial void OnCreatorNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value, "CreateTime");
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifierId
        {
            get
            {
                return _ModifierId;
            }
            set
            {
                OnModifierIdChanging(value);
                ReportPropertyChanging("ModifierId");
                _ModifierId = StructuralObject.SetValidValue(value, "ModifierId");
                ReportPropertyChanged("ModifierId");
                OnModifierIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifierId;
        partial void OnModifierIdChanging(Nullable<global::System.Int32> value);
        partial void OnModifierIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifierName
        {
            get
            {
                return _ModifierName;
            }
            set
            {
                OnModifierNameChanging(value);
                ReportPropertyChanging("ModifierName");
                _ModifierName = StructuralObject.SetValidValue(value, true, "ModifierName");
                ReportPropertyChanged("ModifierName");
                OnModifierNameChanged();
            }
        }
        private global::System.String _ModifierName;
        partial void OnModifierNameChanging(global::System.String value);
        partial void OnModifierNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifyTime
        {
            get
            {
                return _ModifyTime;
            }
            set
            {
                OnModifyTimeChanging(value);
                ReportPropertyChanging("ModifyTime");
                _ModifyTime = StructuralObject.SetValidValue(value, "ModifyTime");
                ReportPropertyChanged("ModifyTime");
                OnModifyTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifyTime;
        partial void OnModifyTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnModifyTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AbandonerId
        {
            get
            {
                return _AbandonerId;
            }
            set
            {
                OnAbandonerIdChanging(value);
                ReportPropertyChanging("AbandonerId");
                _AbandonerId = StructuralObject.SetValidValue(value, "AbandonerId");
                ReportPropertyChanged("AbandonerId");
                OnAbandonerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _AbandonerId;
        partial void OnAbandonerIdChanging(Nullable<global::System.Int32> value);
        partial void OnAbandonerIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AbandonerName
        {
            get
            {
                return _AbandonerName;
            }
            set
            {
                OnAbandonerNameChanging(value);
                ReportPropertyChanging("AbandonerName");
                _AbandonerName = StructuralObject.SetValidValue(value, true, "AbandonerName");
                ReportPropertyChanged("AbandonerName");
                OnAbandonerNameChanged();
            }
        }
        private global::System.String _AbandonerName;
        partial void OnAbandonerNameChanging(global::System.String value);
        partial void OnAbandonerNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AbandonTime
        {
            get
            {
                return _AbandonTime;
            }
            set
            {
                OnAbandonTimeChanging(value);
                ReportPropertyChanging("AbandonTime");
                _AbandonTime = StructuralObject.SetValidValue(value, "AbandonTime");
                ReportPropertyChanged("AbandonTime");
                OnAbandonTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _AbandonTime;
        partial void OnAbandonTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnAbandonTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = StructuralObject.SetValidValue(value, true, "RowVersion");
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DCSModel", Name="ProductAffiProductCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductAffiProductCategory : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ProductAffiProductCategory 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="productCategoryId">ProductCategoryId 属性的初始值。</param>
        /// <param name="productId">ProductId 属性的初始值。</param>
        /// <param name="rootCategoryId">RootCategoryId 属性的初始值。</param>
        public static ProductAffiProductCategory CreateProductAffiProductCategory(global::System.Int32 id, global::System.Int32 productCategoryId, global::System.Int32 productId, global::System.Int32 rootCategoryId)
        {
            ProductAffiProductCategory productAffiProductCategory = new ProductAffiProductCategory();
            productAffiProductCategory.Id = id;
            productAffiProductCategory.ProductCategoryId = productCategoryId;
            productAffiProductCategory.ProductId = productId;
            productAffiProductCategory.RootCategoryId = rootCategoryId;
            return productAffiProductCategory;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductCategoryId
        {
            get
            {
                return _ProductCategoryId;
            }
            set
            {
                OnProductCategoryIdChanging(value);
                ReportPropertyChanging("ProductCategoryId");
                _ProductCategoryId = StructuralObject.SetValidValue(value, "ProductCategoryId");
                ReportPropertyChanged("ProductCategoryId");
                OnProductCategoryIdChanged();
            }
        }
        private global::System.Int32 _ProductCategoryId;
        partial void OnProductCategoryIdChanging(global::System.Int32 value);
        partial void OnProductCategoryIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value, "ProductId");
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.Int32 _ProductId;
        partial void OnProductIdChanging(global::System.Int32 value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RootCategoryId
        {
            get
            {
                return _RootCategoryId;
            }
            set
            {
                OnRootCategoryIdChanging(value);
                ReportPropertyChanging("RootCategoryId");
                _RootCategoryId = StructuralObject.SetValidValue(value, "RootCategoryId");
                ReportPropertyChanged("RootCategoryId");
                OnRootCategoryIdChanged();
            }
        }
        private global::System.Int32 _RootCategoryId;
        partial void OnRootCategoryIdChanging(global::System.Int32 value);
        partial void OnRootCategoryIdChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DCSModel", Name="ProductCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductCategory : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ProductCategory 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="code">Code 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="rootCategoryId">RootCategoryId 属性的初始值。</param>
        /// <param name="status">Status 属性的初始值。</param>
        /// <param name="productCategoryLevel">ProductCategoryLevel 属性的初始值。</param>
        public static ProductCategory CreateProductCategory(global::System.Int32 id, global::System.String code, global::System.String name, global::System.Int32 rootCategoryId, global::System.Int32 status, global::System.Int32 productCategoryLevel)
        {
            ProductCategory productCategory = new ProductCategory();
            productCategory.Id = id;
            productCategory.Code = code;
            productCategory.Name = name;
            productCategory.RootCategoryId = rootCategoryId;
            productCategory.Status = status;
            productCategory.ProductCategoryLevel = productCategoryLevel;
            return productCategory;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false, "Code");
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LayerNodeTypeId
        {
            get
            {
                return _LayerNodeTypeId;
            }
            set
            {
                OnLayerNodeTypeIdChanging(value);
                ReportPropertyChanging("LayerNodeTypeId");
                _LayerNodeTypeId = StructuralObject.SetValidValue(value, "LayerNodeTypeId");
                ReportPropertyChanged("LayerNodeTypeId");
                OnLayerNodeTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _LayerNodeTypeId;
        partial void OnLayerNodeTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnLayerNodeTypeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RootCategoryId
        {
            get
            {
                return _RootCategoryId;
            }
            set
            {
                OnRootCategoryIdChanging(value);
                ReportPropertyChanging("RootCategoryId");
                _RootCategoryId = StructuralObject.SetValidValue(value, "RootCategoryId");
                ReportPropertyChanged("RootCategoryId");
                OnRootCategoryIdChanged();
            }
        }
        private global::System.Int32 _RootCategoryId;
        partial void OnRootCategoryIdChanging(global::System.Int32 value);
        partial void OnRootCategoryIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value, "ParentId");
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Picture
        {
            get
            {
                return _Picture;
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true, "Picture");
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.String _Picture;
        partial void OnPictureChanging(global::System.String value);
        partial void OnPictureChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductCategoryLevel
        {
            get
            {
                return _ProductCategoryLevel;
            }
            set
            {
                OnProductCategoryLevelChanging(value);
                ReportPropertyChanging("ProductCategoryLevel");
                _ProductCategoryLevel = StructuralObject.SetValidValue(value, "ProductCategoryLevel");
                ReportPropertyChanged("ProductCategoryLevel");
                OnProductCategoryLevelChanged();
            }
        }
        private global::System.Int32 _ProductCategoryLevel;
        partial void OnProductCategoryLevelChanging(global::System.Int32 value);
        partial void OnProductCategoryLevelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remark
        {
            get
            {
                return _Remark;
            }
            set
            {
                OnRemarkChanging(value);
                ReportPropertyChanging("Remark");
                _Remark = StructuralObject.SetValidValue(value, true, "Remark");
                ReportPropertyChanged("Remark");
                OnRemarkChanged();
            }
        }
        private global::System.String _Remark;
        partial void OnRemarkChanging(global::System.String value);
        partial void OnRemarkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatorId
        {
            get
            {
                return _CreatorId;
            }
            set
            {
                OnCreatorIdChanging(value);
                ReportPropertyChanging("CreatorId");
                _CreatorId = StructuralObject.SetValidValue(value, "CreatorId");
                ReportPropertyChanged("CreatorId");
                OnCreatorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatorId;
        partial void OnCreatorIdChanging(Nullable<global::System.Int32> value);
        partial void OnCreatorIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CreatorName
        {
            get
            {
                return _CreatorName;
            }
            set
            {
                OnCreatorNameChanging(value);
                ReportPropertyChanging("CreatorName");
                _CreatorName = StructuralObject.SetValidValue(value, true, "CreatorName");
                ReportPropertyChanged("CreatorName");
                OnCreatorNameChanged();
            }
        }
        private global::System.String _CreatorName;
        partial void OnCreatorNameChanging(global::System.String value);
        partial void OnCreatorNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value, "CreateTime");
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifierId
        {
            get
            {
                return _ModifierId;
            }
            set
            {
                OnModifierIdChanging(value);
                ReportPropertyChanging("ModifierId");
                _ModifierId = StructuralObject.SetValidValue(value, "ModifierId");
                ReportPropertyChanged("ModifierId");
                OnModifierIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifierId;
        partial void OnModifierIdChanging(Nullable<global::System.Int32> value);
        partial void OnModifierIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ModifierName
        {
            get
            {
                return _ModifierName;
            }
            set
            {
                OnModifierNameChanging(value);
                ReportPropertyChanging("ModifierName");
                _ModifierName = StructuralObject.SetValidValue(value, true, "ModifierName");
                ReportPropertyChanged("ModifierName");
                OnModifierNameChanged();
            }
        }
        private global::System.String _ModifierName;
        partial void OnModifierNameChanging(global::System.String value);
        partial void OnModifierNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifyTime
        {
            get
            {
                return _ModifyTime;
            }
            set
            {
                OnModifyTimeChanging(value);
                ReportPropertyChanging("ModifyTime");
                _ModifyTime = StructuralObject.SetValidValue(value, "ModifyTime");
                ReportPropertyChanged("ModifyTime");
                OnModifyTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifyTime;
        partial void OnModifyTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnModifyTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AbandonerId
        {
            get
            {
                return _AbandonerId;
            }
            set
            {
                OnAbandonerIdChanging(value);
                ReportPropertyChanging("AbandonerId");
                _AbandonerId = StructuralObject.SetValidValue(value, "AbandonerId");
                ReportPropertyChanged("AbandonerId");
                OnAbandonerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _AbandonerId;
        partial void OnAbandonerIdChanging(Nullable<global::System.Int32> value);
        partial void OnAbandonerIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AbandonerName
        {
            get
            {
                return _AbandonerName;
            }
            set
            {
                OnAbandonerNameChanging(value);
                ReportPropertyChanging("AbandonerName");
                _AbandonerName = StructuralObject.SetValidValue(value, true, "AbandonerName");
                ReportPropertyChanged("AbandonerName");
                OnAbandonerNameChanged();
            }
        }
        private global::System.String _AbandonerName;
        partial void OnAbandonerNameChanging(global::System.String value);
        partial void OnAbandonerNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AbandonTime
        {
            get
            {
                return _AbandonTime;
            }
            set
            {
                OnAbandonTimeChanging(value);
                ReportPropertyChanging("AbandonTime");
                _AbandonTime = StructuralObject.SetValidValue(value, "AbandonTime");
                ReportPropertyChanged("AbandonTime");
                OnAbandonTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _AbandonTime;
        partial void OnAbandonTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnAbandonTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = StructuralObject.SetValidValue(value, true, "RowVersion");
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MarshallingSequence
        {
            get
            {
                return _MarshallingSequence;
            }
            set
            {
                OnMarshallingSequenceChanging(value);
                ReportPropertyChanging("MarshallingSequence");
                _MarshallingSequence = StructuralObject.SetValidValue(value, "MarshallingSequence");
                ReportPropertyChanged("MarshallingSequence");
                OnMarshallingSequenceChanged();
            }
        }
        private Nullable<global::System.Int32> _MarshallingSequence;
        partial void OnMarshallingSequenceChanging(Nullable<global::System.Int32> value);
        partial void OnMarshallingSequenceChanged();

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DCSModel", Name="TiledRegion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TiledRegion : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TiledRegion 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static TiledRegion CreateTiledRegion(global::System.Int32 id)
        {
            TiledRegion tiledRegion = new TiledRegion();
            tiledRegion.Id = id;
            return tiledRegion;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegionName
        {
            get
            {
                return _RegionName;
            }
            set
            {
                OnRegionNameChanging(value);
                ReportPropertyChanging("RegionName");
                _RegionName = StructuralObject.SetValidValue(value, true, "RegionName");
                ReportPropertyChanged("RegionName");
                OnRegionNameChanged();
            }
        }
        private global::System.String _RegionName;
        partial void OnRegionNameChanging(global::System.String value);
        partial void OnRegionNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProvinceName
        {
            get
            {
                return _ProvinceName;
            }
            set
            {
                OnProvinceNameChanging(value);
                ReportPropertyChanging("ProvinceName");
                _ProvinceName = StructuralObject.SetValidValue(value, true, "ProvinceName");
                ReportPropertyChanged("ProvinceName");
                OnProvinceNameChanged();
            }
        }
        private global::System.String _ProvinceName;
        partial void OnProvinceNameChanging(global::System.String value);
        partial void OnProvinceNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CityName
        {
            get
            {
                return _CityName;
            }
            set
            {
                OnCityNameChanging(value);
                ReportPropertyChanging("CityName");
                _CityName = StructuralObject.SetValidValue(value, true, "CityName");
                ReportPropertyChanged("CityName");
                OnCityNameChanged();
            }
        }
        private global::System.String _CityName;
        partial void OnCityNameChanging(global::System.String value);
        partial void OnCityNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CountyName
        {
            get
            {
                return _CountyName;
            }
            set
            {
                OnCountyNameChanging(value);
                ReportPropertyChanging("CountyName");
                _CountyName = StructuralObject.SetValidValue(value, true, "CountyName");
                ReportPropertyChanged("CountyName");
                OnCountyNameChanged();
            }
        }
        private global::System.String _CountyName;
        partial void OnCountyNameChanging(global::System.String value);
        partial void OnCountyNameChanged();

        #endregion

    }

    #endregion

}
